### PR TITLE
Added Request data to parameter "ZF\ContentValidation\ParameterData" for before validation event usage

### PR DESCRIPTION
**Pull request by developer-devPHP**
Added request data to ZF\ContentValidation\ParameterData using setParam to allow modification in custom before validation events if needed.

### CODE REVIEW

**Comment by developer-devPHP** [comment]
Can someone review this changes and if it ok for you merge with next release.
I think this can be helpful.

**Comment by developer-devPHP** [comment]
@weierophinney  could you please review this changes?

**Comment by weierophinney** [comment]
I'm just finishing up ZendCon; I'll review these next week.

**Comment by developer-devPHP** [comment]
Thank you @weierophinney

**Comment by weierophinney** [comment]
I'm trying to understand the purpose behind this.

The data is already available in the event in several ways:

- via the request itself (raw data)
- via the `ZFContentNegotiationParameterData` parameter (parsed data; particularly of import for JSON/XML request payloads and/or those with file uploads)
- via the input filter (if you can safely ignore values the input filter does not know about)

Now, both of these require you know the request method before you retrieve the data from them, which could be an argument for pulling the data into another event parameter. However, I'd argue we shouldn't have _yet another copy of the data_.

Can you provide a full use case for this, so we can determine if there is a need for the feature, or if there is another way to go about it?

Thanks!

**Comment by developer-devPHP** [comment]
The idea is not have a method to get data and use it, because you are right, have other methods and functionality to do it.
The idea is to have a chance to do manipulation with data during custom EVENT_BEFORE_VALIDATE actions.
For example to add any extra data or change it. During this we can add our custom functionality to add rout params data.

So main idea is last action
```php 
$data = ArrayUtils::merge($data, $e->getParam('ZF\ContentValidation\ParameterData'), true);
```
after this changes we can have a main data and custom data as one array and continue our validation processes.
This will not effect to any other functionality if we are not using it.

**Comment by developer-devPHP** [comment]
@weierophinney  any other comments to my changes? 
Can you include this changes to next release?

**Comment by developer-devPHP** [comment]
@weierophinney Can you update status of this pull request?

**Comment by weierophinney** [comment]
I finally understand the idea around this; it can help facilitate, for instance, pulling route parameters (such as an identifier), and adding them to the data to validate. This would essentially provide an alternative to #89 and #92: users would add a listener to EVENT_BEFORE_VALIDATE (which receives an `MvcEvent`, and thus all its collaborators, including the `RouteMatch`), manipulate the data as necessary, and push it back into the event. The original data is then merged with whatever is in the event before validation:

```php
$events->listen(ContentValidationListener::EVENT_BEFORE_VALIDATE, function ($e) {
    if ($e->getController() !== MyRestController::class) {
        return;
    }

    $matches = $e->getRouteMatch();
    $data = $e->getParam('ZF\ContentValidation\ParameterData') ?: [];
    $data['id'] = $matches->getParam('id');
    $e->setParam('ZF\ContentValidation\ParameterData', $data);
});
```

I like this approach; it's minimal, completely opt-in, and provides some nice flexibility with regards to aggregating and validation data from a variety of sources.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.4.0.

**Pull request closed without merging**
