### PR TITLE
Resolves Issue #37 - Allow modification of InputFilter before validation

### PR DESCRIPTION
**Pull request by steverhoades**
Example Usage:
```
use Zend\EventManager\SharedListenerAggregateInterface;
use Zend\Mvc\MvcEvent;
use Zend\Validator\Db\NoRecordExists;
use ZF\ContentValidation\ContentValidationListener

class SomeValidationListener implements SharedListenerAggregateInterface
{
    public function attachShared(SharedEventManagerInterface $events)
    {
        // trigger after authentication/authorization and content negotiation
        $this->listeners[] = $events->attach(
            'ZF\ContentValidation\ContentValidationListener',
            ZFValidationListener::EVENT_BEFORE_VALIDATE,
            array($this, 'beforeValidate')
        );
    }

    public function detachShared(SharedEventManagerInterface $events)
    {
        foreach ($this->listeners as $index => $callback) {
            if ($events->detach($callback)) {
                unset($this->listeners[$index]);
            }
        }
    }

    public function beforeValidate(MvcEvent $e)
    {
        if($e->getRequest()->getMethod() !== 'PUT') {
            return;
        }

        $matches = $e->getRouteMatch();
        $controller = $matches->getParam('controller', false);

        $inputFilter = $e->getParam('ZF\ContentValidation\InputFilter', false);
        if (! $inputFilter) {
            return;
        }

        // look for controllers of interest.
        switch($controller) {
            case 'CompanyAdmin\V1\Rest\Users\Controller':
                $id = $matches->getParam('user_id');
                break;
            default:
                return;
        }

        $input = $inputFilter->get('username');
        $chain = $input->getValidatorChain();

        foreach ($chain->getValidators() as $validator) {
            if (! $validator['instance'] instanceof NoRecordExists) {
                continue;
            }

            $validator['instance']->setExclude(array(
                'field' => 'id',
                'value' => $id,
            ));
            break;
        }
    }
}
```

### CODE REVIEW

**Comment by weierophinney** [comment]
Cool feature! Can you please add unit tests, @steverhoades ? (feature freeze for 1.1 is late this week)

**Comment by steverhoades** [comment]
@weierophinney added unit tests, not sure how i missed that one.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.1.

**Comment by diwms** [comment]
Could you please add this feature with usage example to readme? Because it's really useful, but not all know how to use it

**Comment by fndmiranda** [comment]
I also can not use the resource, could exemplify?

**Comment by intellent** [comment]
Here’s a simple example that expects you to have a route like /entities/:id and modifies the NoRecordExists validator of a unique field named 'alias'.

Put this in your Module.php:

    public function onBootstrap(MvcEvent $e)
    {
        $serviceManager = $e->getApplication()->getServiceManager();

        $events = $serviceManager->get('ZF\ContentValidation\ContentValidationListener')->getEventManager();

        $events->attach('contentvalidation.beforevalidate', function(MvcEvent $e)
        {
            $inputFilter = $e->getParam('ZF\ContentValidation\InputFilter');

            $alias = $inputFilter->get('alias');
            $validatorChain = $alias->getValidatorChain();

            foreach ($validatorChain->getValidators() as $validator) {
                if (! $validator['instance'] instanceof NoRecordExists) {
                    continue;
                }

                $validator['instance']->setExclude(array(
                    'field' => 'id',
                    'value' => intval($e->getRouteMatch()->getParam('id')),
                ));
                break;
            }
        });
    }

**Pull request closed without merging**
