### PR TITLE
Allow to validate request body data for delete.

### PR DESCRIPTION
**Pull request by ruzann**

### CODE REVIEW

**Comment by webimpress** [comment]
@ruzann We need a test case for that change.

**Comment by ruzann** [comment]
@webimpress can you please review?

**Comment by webimpress** [comment]
@ruzann We still need test case, so test `DELETE` request __with__ body.

**Comment by ruzann** [comment]
@webimpress can you please review?

**Comment by webimpress** [comment]
@ruzann I just did a quick test:
- checkout your PR,
- composer install
- run tests (all green) 👍 
- bring back line 61 in `src/ContentValidationListener.php`: https://github.com/zfcampus/zf-content-validation/pull/98/files#diff-b4f3c09c100c9a271d830e179c3eaa65L61
- run tests again ... still all green (at this point both added tests should fail).

So without analysing tests I know that those are wrong.

Sorry, I don't have time to analyze them now. Hope you will have time to check it again and make a proper fixes to test, to really cover the change you provided in the pr.

**Comment by ruzann** [comment]
@webimpress I fixed the tests.

**Comment by spectravp** [comment]
This has created a backwards compatibility break, or at least an expectation break. In the absence of a DELETE key under the zf-content-validation configuration key, Apigility assumes it should use the default input filter. Now any DELETE requests that have no body, using type DELETE to Url: /some-api-endpoint/some-id fails validation unless:

1) A valid body is provided, which is seldom intended, required or efficient when you are just trying to delete a resource. 
2) You explicitly set 'DELETE' => false

I just had to update nearly a hundred API endpoints for this. In the absence of a DELETE key, the behavior should not break expectations. It should only invoke the input filter if the DELETE key is set and is not false.

**Comment by developer-devPHP** [comment]
@spectravp #99 pull request fixes should solve your problem, but currently this is not merged yet.

**Comment by weierophinney** [comment]
@spectravp #99 has been merged, and released with 1.6.1.

**Pull request merged**
