### PR TITLE
Fix typo #68

### PR DESCRIPTION
**Pull request by thomasvargiu**
Fix for #68

### CODE REVIEW

**Comment by AdilHoumadi** [comment]
@thomasvargiu, Thanks for your PR.
@weierophinney, can you check this fix. a regression was introduced in the last migration!
Thanks.

**Comment by AdilHoumadi** [comment]
The PR does not fix all the issues, 
```php
Validator\DbRecordExists::class => Validator\Db\RecordExistsFactory::class,
Validator\DbNoRecordExists::class => Validator\Db\NoRecordExistsFactory::class,
```
This mapping is not correct, we don't have any class with this names (DbRecordExists or DbNoRecordExists) in this namespace,(namespace ZF\ContentValidation) and the ContentValidationListenerFactory class must implements FactoryInterface to insure the backwards compatibility

**Comment by AdilHoumadi** [comment]
I create a PR including the fix proposed by @thomasvargiu,
Here is my PR : #71

**Comment by thomasvargiu** [comment]
@AdilHoumadi I agree.
I propose to close this PR in favor of #71.

**Pull request closed without merging**
